# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='Username:')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия:')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя:')),
                ('login', models.CharField(max_length=32, verbose_name='Ваш Логин:')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль для доступа к ЛК:')),
                ('confirmpassword', models.CharField(max_length=32, verbose_name='Подтвердите пароль:')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail:')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Контактный номер:')),
                ('status', models.CharField(choices=[('Администратор', 'Администратор'), ('Пользователь', 'Пользователь')], default='Пользователь', max_length=32, verbose_name='Выберите Ваш статус пользователя:')),
                ('photo', models.ImageField(blank=True, upload_to='static/img/avatars/', verbose_name='Загрузите Ваше главное фото:')),
                ('rules', models.BooleanField(max_length=32)),
            ],
        ),
    ]
