# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20170626_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, default=None, verbose_name='Дата рождения:'),
        ),
    ]
