# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_person_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
    ]
