# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 17:39
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_remove_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Контактный номер:'),
        ),
    ]
