# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_auto_20170702_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='../media/img/avatars/', verbose_name='Загрузите Ваше главное фото:'),
        ),
    ]
