# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_auto_20170702_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='avatar',
            new_name='photo',
        ),
    ]
