# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='key_word')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source_manager.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_manager.Persons'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_manager.Persons'),
        ),
    ]
